server:
  port: 8087
spring:
  application:
    name: kgms-growth
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/kgms
    username: root
    password: tldevops2026
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
