services:
  mysql:
    image: mysql:8.0
    container_name: kgms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kindergarten
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: kgms-redis
    ports:
      - "6379:6379"

  nacos:
    image: nacos/nacos-server:latest
    container_name: kgms-nacos
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8888:8080"

volumes:
  mysql_data:
