services:
  mysql:
    image: mysql:8.0
    container_name: kgms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kindergarten
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: kgms-redis
    ports:
      - "6379:6379"

  nacos:
    image: nacos/nacos-server:latest
    container_name: kgms-nacos
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql

volumes:
  mysql_data:
