version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kgms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --skip-networking

  redis:
    image: redis:7-alpine
    container_name: kgms-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: