server:
  port: 8089
spring:
  application:
    name: kgms-notice
  datasource:
    url: jdbc:mysql://localhost:3307/kgms
    username: root
    password: tldevops2026
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
