server:
  port: 8080

spring:
  application:
    name: kgms-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务
        - id: kgms-user
          uri: lb://kgms-user
          predicates:
            - Path=/api/user/**

        # 学生服务
        - id: kgms-student
          uri: lb://kgms-student
          predicates:
            - Path=/api/student/**
          filters:
            - StripPrefix=1

        # 班级服务
        - id: kgms-class
          uri: lb://kgms-class
          predicates:
            - Path=/api/class/**
          filters:
            - StripPrefix=1

        # 成长记录服务
        - id: kgms-record
          uri: lb://kgms-record
          predicates:
            - Path=/api/record/**
          filters:
            - StripPrefix=1

        # 食谱服务
        - id: kgms-food
          uri: lb://kgms-food
          predicates:
            - Path=/api/food/**
          filters:
            - StripPrefix=1

        # 课程服务
        - id: kgms-course
          uri: lb://kgms-course
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=1

        # 成长AI服务
        - id: kgms-growth
          uri: lb://kgms-growth
          predicates:
            - Path=/api/growth/**
          filters:
            - StripPrefix=1

        # 视频服务
        - id: kgms-video
          uri: lb://kgms-video
          predicates:
            - Path=/api/video/**
          filters:
            - StripPrefix=1

        # 通知服务
        - id: kgms-notice
          uri: lb://kgms-notice
          predicates:
            - Path=/api/notice/**
          filters:
            - StripPrefix=1
