server:
  port: 8084
spring:
  application:
    name: kgms-record
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/kgms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tldevops2026
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
