server:
  port: 8083
spring:
  application:
    name: kgms-class
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kgms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tldevops2026
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
